// Centralized theme and style constants for the entire frontend
export const THEME = {
  // Card and poster
  posterWidth: 210,
  posterHeight: 315,
  borderRadius: 6,
  cardPadding: 16,
  cardGap: 16,
  cardMarginBottom: 24,
  fontSize: 14,
  fontSizeTitle: 18,
  colorDark: '#23242a',
  colorLight: '#fafafa',
  colorTextDark: '#f3f3f3',
  colorTextLight: '#222',
  colorBoxShadowDark: '0 1px 8px #0004',
  colorBoxShadowLight: '0 1px 4px #0001',
  colorBoxShadowDarkHover: '0 4px 24px #0006',
  colorBoxShadowLightHover: '0 2px 8px #0002',
  colorPosterBgDark: '#23242a',
  colorPosterBgLight: '#eee',
  colorNoImageBg: '#444',
  colorNoImageText: '#888',
  colorOverviewDark: '#e0e0e0',
  colorOverviewLight: '#444',
  colorOriginalTitleDark: '#b0b0b0',
  colorOriginalTitleLight: '#888',
  colorButtonRemove: '#f44336',
  colorButtonAddDark: '#1976d2',
  colorButtonAddLight: '#cce',
  colorButtonText: '#fff',
  fontWeightButton: 500,

  // MovieDetail specific
  containerMaxWidth: 900,
  containerPadding: 24,
  containerTextAlign: 'left',
  containerPosition: 'relative',
  backdropHeight: 420,
  backdropBorderRadius: 16,
  backdropOpacity: 0.7,
  backdropZIndex: 0,
  contentZIndex: 1,
  contentMinHeightWithBackdrop: 320,
  contentMarginTopWithBackdrop: 300,
  contentMarginTopNoBackdrop: 60,
  posterBoxShadow: '0 4px 24px #0006',
  posterMarginTop: -20,
  posterBackground: '#23242a',
  noImageBackground: '#444',
  noImageColor: '#888',
  noImageFontSize: 16,
  buttonBackColor: '#90caf9',
  buttonBackFontWeight: 500,
  buttonBackFontSize: 16,
  buttonBackBorderRadius: 6,
  titleFontSize: 32,
  titleColor: '#fff',
  directorColor: '#90caf9',
  directorFontWeight: 500,
  directorMarginBottom: 8,
  originalTitleColor: '#b0b0b0',
  originalTitleFontStyle: 'italic',
  originalTitleMarginBottom: 12,
  overviewColor: '#e0e0e0',
  overviewEmptyColor: '#888',
  releaseDateColor: '#fff',
  ratingColor: '#90caf9',
  ratingFontWeight: 500,
  ratingOutOfColor: '#b0b0b0',
  genresColor: '#fff',
  buttonRemoveColor: '#f44336',
  buttonAddBackground: '#1976d2',
  buttonAddColor: '#fff',
  buttonBorderRadius: 6,
  buttonPadding: '8px 18px',
  buttonFontWeight: 500,
  mainCastTitleColor: '#fff',
  mainCastTitleMarginBottom: 16,
  mainCastMarginTop: 40,
  actorCardWidth: 120,
  actorImageWidth: 90,
  actorImageHeight: 120,
  actorImageBorderRadius: 8,
  actorImageBoxShadow: '0 2px 8px #0006',
  actorNoImageBackground: '#444',
  actorNoImageColor: '#888',
  actorNameFontWeight: 500,
  actorCharacterColor: '#b0b0b0',
  actorCharacterFontSize: 13,

  // --- Composite style objects for components ---
  buttonBase: {
    border: 'none',
    borderRadius: 6,
    padding: '8px 18px',
    fontWeight: 500,
    fontSize: 16,
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  buttonAdd: {
    background: '#1976d2',
    color: '#fff',
  },
  buttonRemove: {
    color: '#f44336',
  },
  buttonBack: {
    background: 'none',
    color: '#646cff',
    border: 'none',
    borderRadius: 6,
    fontWeight: 500,
    fontSize: 16,
    padding: '6px 16px',
    marginBottom: 12,
    cursor: 'pointer',
  },
  posterStyle: {
    width: 210,
    height: 315,
    borderRadius: 6,
    boxShadow: '0 4px 24px #0006',
    background: '#23242a',
    marginRight: 24,
  },
  posterFallback: {
    width: 210,
    height: 315,
    borderRadius: 6,
    background: '#444',
    color: '#888',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    marginRight: 24,
  },
  detailContainer: {
    maxWidth: 900,
    margin: '0 auto',
    padding: 24,
    color: '#fafafa',
  },
  backdropWrapper: {
    top: 0,
    left: 0,
    width: '100%',
    height: 420,
    zIndex: 0,
    borderRadius: 16,
    overflow: 'hidden',
  },
  backdropImage: {
    width: '100%',
    height: '100%',
    opacity: 0.7,
    display: 'block',
  },
  backdropOverlay: {
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: 'linear-gradient(to top, #23242a 0%, #23242a88 40%, #23242a00 80%)',
  },
  detailContent: (hasBackdrop: boolean) => ({
    zIndex: 2,
    minHeight: hasBackdrop ? 320 : 0,
    marginTop: hasBackdrop ? 300 : 60,
    background: 'none',
  }),
  detailRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 32,
  },
  detailInfo: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: 32,
    color: '#fff',
    margin: '0 0 8px 0',
  },
  director: {
    color: '#90caf9',
    fontWeight: 500,
    marginBottom: 8,
  },
  originalTitle: {
    color: '#b0b0b0',
    fontStyle: 'italic',
    marginBottom: 12,
  },
  overview: {
    color: '#e0e0e0',
    marginBottom: 12,
  },
  overviewEmpty: {
    color: '#888',
    fontStyle: 'italic',
  },
  releaseDate: {
    color: '#fff',
  },
  rating: {
    color: '#90caf9',
    fontWeight: 500,
  },
  ratingOutOf: {
    color: '#b0b0b0',
  },
  genres: {
    color: '#fff',
  },
  mainCastTitle: {
    color: '#fff',
    marginBottom: 16,
    fontSize: 18,
    fontWeight: 500,
  },
  castListRow: {
    display: 'flex',
    gap: 24,
  },
  actorCard: {
    width: 120,
    marginBottom: 12,
  },
  actorImage: {
    width: 90,
    height: 120,
    borderRadius: 8,
    boxShadow: '0 2px 8px #0006',
    margin: '0 auto 8px auto',
    display: 'block',
  },
  actorNoImage: {
    width: 90,
    height: 120,
    borderRadius: 8,
    background: '#444',
    color: '#888',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 32,
    margin: '0 auto 8px auto',
  },
  actorName: {
    fontWeight: 500,
    color: '#fff',
    fontSize: 15,
  },
  actorCharacter: {
    color: '#b0b0b0',
    fontSize: 13,
  },
  listPanelContainer: {
    maxWidth: 900,
    margin: '0 auto',
    padding: 24,
    background: 'none',
  },
  listPanelTitle: {
    fontSize: 24,
    fontWeight: 600,
    margin: '0 0 24px 0',
    color: '#fff',
  },
  listPanelLoading: {
    color: '#888',
    fontSize: 16,
    margin: '24px 0',
  },
  listPanelError: {
    color: '#f44336',
    fontSize: 16,
    margin: '24px 0',
  },
  listPanelList: {
    listStyle: 'none',
    padding: 0,
    maxWidth: 700,
    margin: '0 auto',
  },
  listPanelEmpty: {
    fontSize: 16,
    color: '#888',
    margin: '32px 0',
  },
  paginationButton: {
    background: '#1976d2',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    padding: '8px 18px',
    fontWeight: 500,
    fontSize: 16,
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  paginationButtonDisabled: {
    background: '#b0b0b0',
    color: '#fff',
    cursor: 'not-allowed',
    opacity: 0.7,
  },
};
